name: CI - Clonando app y ejecutando test

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:

  test:
    runs-on: ubuntu-latest
    services: 
      mongo:
        image: mongo:6.0
        ports: 
        - 27017:27017

    env: 
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: 6007
      VITE_API_URL: http://localhost:6007/api

    steps:
    - name: Checkout repo actula (con el workflow)
      uses: actions/checkout@v3

    - name: Clonar repo athena redux bank
      run:
        git clone https://github.com/fsosa9jobs/redux-athena-bank.git app           

    - name: Crear archivo .env para backend
      run: |
          
          echo "MONGO_URI: ${{ env.MONGO_URI }}" > app/backend/.env
          echo "JWT_SECRET: ${{ env.JWT_SECRET }}" > app/backend/.env
          echo "PORT: 6007" > app/backend/.env
          echo "VITE_API_URL: ${{ env.VITE_API_URL }}" > app/backend/.env

    - name: Instalar dependencias de backend
      run: |
        cd app/backend
        npm install

    - name: Construir backend
      run: |
        cd app/backend
        npm run dev > backend.log 2>&1 &
    
    #se instala la herramienta wait-on globalmente
    - name: Instalar wait-on
      run: npm install -g wait-on

    #esperar que el backend se levnte ne le puerto 6007
    - name: esperando backend
      run : wait-on tcp:6007

    #instalar dependencias del frontend
    - name: instalar dependencias frontend
      run: |
        cd app/frontend
        npm install
      env: 
        VITE_API_URL: ${{ env.VITE_API_URL}}

    - name: Construir backfrontendend
      run: |
        cd app/frontend
        npm run dev > frontend.log 2>&1 &

    #esperar que se levante el fron
    - name: esperando frontend
      run : wait-on http://localhost:3000

    #empezr a ejecutar las pruebas
    - name: Instalr y ejecutar pruebas
      run: |
        cd tests
        npm install
        npx playwright install --with-deps
        npx playwright test --reporter=html

    - name: Guardar reportes como artefactos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path:  ./playwright-report

    - name: Deploy Playwright report to GitHub Pages
      if: always()
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clonar gh-pages branch en carpeta temporal
          cd $RUNNER_TEMP
          git clone --depth=1 --branch=gh-pages https://x-access-token:${{ secrets.GH_PAGES_PAT }}@github.com/${{ github.repository }} gh-pages

          cd gh-pages

          # Limpiar contenido viejo
          rm -rf ./*

          # Copiar nuevo contenido del reporte
          mkdir -p report-${GITHUB_RUN_NUMBER}
          cp -r $GITHUB_WORKSPACE/playwright-report/* ./report-${GITHUB_RUN_NUMBER}


          # Commit y push
          git add .
          git commit -m "Reporte Playwright - Build $GITHUB_RUN_NUMBER"
          git push origin gh-pages

    - name: Imprimir link en la consola
      if: always()
      run: |
          echo "reporte disponible en: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/report-${{ github.run_number }}/"
